declare -A MOCK_CONTAINER
MOCK_CONTAINER["x86_64"]="epel-6-pmm-x86_64"
MOCK_CONTAINER["aarch64"]="alma+epel-8-pmm-aarch64"

declare -A ERLANG_PACKAGE
ERLANG_PACKAGE["x86_64"]="pmm-erlang"
ERLANG_PACKAGE["aarch64"]="pmm-erlang"

declare -A ERLANG_VERSION
ERLANG_VERSION["x86_64"]="< 22"
ERLANG_VERSION["aarch64"]="< 22"
