#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage:   make_tar VERSION OS"
    echo "Example: make_tar 1.2.1 centos6"
    exit 1
fi

version=$1
os=$2

arch=`uname -m`

dir_name=smppload-${version}
tar_name=smppload-${version}-${os}.${arch}.tar.gz

cp -r smppload ${dir_name}

cp -r meta ${dir_name}/
echo ${version} > ${dir_name}/meta/VERSION
echo ${os}.${arch} > ${dir_name}/meta/RELEASE

tar cfz ${tar_name} ${dir_name}/*
