#!/bin/sh

SELF=${0}
SCRIPT_NAME=$(basename ${SELF})

LINK=$(readlink ${SELF})
if [ ! -z ${LINK} ]; then
    SCRIPT_DIR=$(dirname ${LINK})
else
    SCRIPT_DIR=$(dirname ${SELF})
fi

${SCRIPT_DIR}/bin/${SCRIPT_NAME} script "$*"
